packages:
  - packages/*
onlyBuiltDependencies:
  - unrs-resolver
ignoredBuiltDependencies:
  - esbuild
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  unrs-resolver: false
